# Generated by Django 2.2.2 on 2019-08-31 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', null=True)),
                ('location', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('contact', models.IntegerField(blank=True, default=9876543210, null=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('test', models.TextField(blank=True, default='', null=True)),
                ('timing', models.TimeField(default=django.utils.timezone.now)),
                ('availability', models.BooleanField(default=True)),
                ('certified', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
