# Generated by Django 2.2.2 on 2019-08-31 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labs',
            name='joined_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
