# Generated by Django 2.2.2 on 2019-08-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_labs_joined_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labs',
            name='contact',
            field=models.TextField(blank=True, default='9876543210', null=True),
        ),
    ]
