# Generated by Django 2.2.2 on 2019-09-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190831_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='labs',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
